name: Build and Publish

on:
    create:
        tags:
            - v*

jobs:
    publish:
        name: Build and publishing package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm install
            - run: npm run build-prod
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_AUTH_TOKEN }}
