name: Documentation

on:
    push:
        branches:
            - develop

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Copy README file
              uses: canastro/copy-file-action@master
              with:
                  source: "README.md"
                  target: "docs/README.md"
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: ./docs
                  CLEAN: true
