name: Documentation

on:
    push:
        branches:
            - develop

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              run: cp ./README.md ./docs
            - uses: tool3/docsify-action@master
              with:
                  branch: develop
                  github_token: ${{ secrets.GITHUB_TOKEN }}
