name: Documentation

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: tool3/docsify-action@v1
              with:
                  branch: develop
                  github_token: ${{ secrets.GITHUB_TOKEN }}
